package com.zcadmin.entity;
// Generated 2016-5-1 17:34:38 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "gmczc")
public class Address implements java.io.Serializable {

	private AddressId id;
	private String addressName;
	private String addressPhone;
	private String addressProvince;
	private String addressCity;
	private String addressDistrict;
	private String addressDetial;

	public Address() {
	}

	public Address(AddressId id, String addressName, String addressPhone, String addressProvince, String addressCity,
			String addressDistrict, String addressDetial) {
		this.id = id;
		this.addressName = addressName;
		this.addressPhone = addressPhone;
		this.addressProvince = addressProvince;
		this.addressCity = addressCity;
		this.addressDistrict = addressDistrict;
		this.addressDetial = addressDetial;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id", nullable = false) ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false) ) })
	public AddressId getId() {
		return this.id;
	}

	public void setId(AddressId id) {
		this.id = id;
	}

	@Column(name = "address_name", nullable = false, length = 10)
	public String getAddressName() {
		return this.addressName;
	}

	public void setAddressName(String addressName) {
		this.addressName = addressName;
	}

	@Column(name = "address_phone", nullable = false, length = 11)
	public String getAddressPhone() {
		return this.addressPhone;
	}

	public void setAddressPhone(String addressPhone) {
		this.addressPhone = addressPhone;
	}

	@Column(name = "address_province", nullable = false, length = 45)
	public String getAddressProvince() {
		return this.addressProvince;
	}

	public void setAddressProvince(String addressProvince) {
		this.addressProvince = addressProvince;
	}

	@Column(name = "address_city", nullable = false, length = 45)
	public String getAddressCity() {
		return this.addressCity;
	}

	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}

	@Column(name = "address_district", nullable = false, length = 45)
	public String getAddressDistrict() {
		return this.addressDistrict;
	}

	public void setAddressDistrict(String addressDistrict) {
		this.addressDistrict = addressDistrict;
	}

	@Column(name = "address_detial", nullable = false, length = 200)
	public String getAddressDetial() {
		return this.addressDetial;
	}

	public void setAddressDetial(String addressDetial) {
		this.addressDetial = addressDetial;
	}

}
