package com.zcadmin.entity;
// Generated 2016-5-1 17:34:38 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddressId generated by hbm2java
 */
@Embeddable
public class AddressId implements java.io.Serializable {

	private int addressId;
	private int userId;

	public AddressId() {
	}

	public AddressId(int addressId, int userId) {
		this.addressId = addressId;
		this.userId = userId;
	}

	@Column(name = "address_id", nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddressId))
			return false;
		AddressId castOther = (AddressId) other;

		return (this.getAddressId() == castOther.getAddressId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAddressId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
