package com.zcadmin.entity;
// Generated 2016-5-1 17:34:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "gmczc")
public class Orders implements java.io.Serializable {

	private Integer orderId;
	private int userId;
	private int projectId;
	private int returnId;
	private String address;
	private Date orderTime;
	private String orderState;
	private String logistics;

	public Orders() {
	}

	public Orders(int userId, int projectId, int returnId, String address, Date orderTime, String orderState) {
		this.userId = userId;
		this.projectId = projectId;
		this.returnId = returnId;
		this.address = address;
		this.orderTime = orderTime;
		this.orderState = orderState;
	}

	public Orders(int userId, int projectId, int returnId, String address, Date orderTime, String orderState,
			String logistics) {
		this.userId = userId;
		this.projectId = projectId;
		this.returnId = returnId;
		this.address = address;
		this.orderTime = orderTime;
		this.orderState = orderState;
		this.logistics = logistics;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "return_id", nullable = false)
	public int getReturnId() {
		return this.returnId;
	}

	public void setReturnId(int returnId) {
		this.returnId = returnId;
	}

	@Column(name = "address", nullable = false, length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_time", nullable = false, length = 19)
	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	@Column(name = "order_state", nullable = false, length = 6)
	public String getOrderState() {
		return this.orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	@Column(name = "logistics", length = 45)
	public String getLogistics() {
		return this.logistics;
	}

	public void setLogistics(String logistics) {
		this.logistics = logistics;
	}

}
