package com.zcadmin.entity;
// Generated 2016-5-1 17:34:38 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrderView generated by hbm2java
 */
@Entity
@Table(name = "order_view", catalog = "gmczc")
public class OrderView implements java.io.Serializable {

	private OrderViewId id;

	public OrderView() {
	}

	public OrderView(OrderViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false) ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false) ),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id", nullable = false) ),
			@AttributeOverride(name = "returnId", column = @Column(name = "return_id", nullable = false) ),
			@AttributeOverride(name = "returnImage", column = @Column(name = "return_image", length = 100) ),
			@AttributeOverride(name = "orderTime", column = @Column(name = "order_time", nullable = false, length = 19) ),
			@AttributeOverride(name = "supportMoney", column = @Column(name = "support_money", nullable = false) ),
			@AttributeOverride(name = "orderState", column = @Column(name = "order_state", nullable = false, length = 6) ),
			@AttributeOverride(name = "projectTitle", column = @Column(name = "project_title", nullable = false, length = 80) ),
			@AttributeOverride(name = "projectHead", column = @Column(name = "project_head", length = 100) ),
			@AttributeOverride(name = "address", column = @Column(name = "address", nullable = false, length = 300) ),
			@AttributeOverride(name = "logistics", column = @Column(name = "logistics", length = 45) ) })
	public OrderViewId getId() {
		return this.id;
	}

	public void setId(OrderViewId id) {
		this.id = id;
	}

}
