package com.zcadmin.entity;
// Generated 2016-5-1 17:34:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderViewId generated by hbm2java
 */
@Embeddable
public class OrderViewId implements java.io.Serializable {

	private int orderId;
	private int userId;
	private int projectId;
	private int returnId;
	private String returnImage;
	private Date orderTime;
	private int supportMoney;
	private String orderState;
	private String projectTitle;
	private String projectHead;
	private String address;
	private String logistics;

	public OrderViewId() {
	}

	public OrderViewId(int orderId, int userId, int projectId, int returnId, Date orderTime, int supportMoney,
			String orderState, String projectTitle, String address) {
		this.orderId = orderId;
		this.userId = userId;
		this.projectId = projectId;
		this.returnId = returnId;
		this.orderTime = orderTime;
		this.supportMoney = supportMoney;
		this.orderState = orderState;
		this.projectTitle = projectTitle;
		this.address = address;
	}

	public OrderViewId(int orderId, int userId, int projectId, int returnId, String returnImage, Date orderTime,
			int supportMoney, String orderState, String projectTitle, String projectHead, String address,
			String logistics) {
		this.orderId = orderId;
		this.userId = userId;
		this.projectId = projectId;
		this.returnId = returnId;
		this.returnImage = returnImage;
		this.orderTime = orderTime;
		this.supportMoney = supportMoney;
		this.orderState = orderState;
		this.projectTitle = projectTitle;
		this.projectHead = projectHead;
		this.address = address;
		this.logistics = logistics;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "return_id", nullable = false)
	public int getReturnId() {
		return this.returnId;
	}

	public void setReturnId(int returnId) {
		this.returnId = returnId;
	}

	@Column(name = "return_image", length = 100)
	public String getReturnImage() {
		return this.returnImage;
	}

	public void setReturnImage(String returnImage) {
		this.returnImage = returnImage;
	}

	@Column(name = "order_time", nullable = false, length = 19)
	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	@Column(name = "support_money", nullable = false)
	public int getSupportMoney() {
		return this.supportMoney;
	}

	public void setSupportMoney(int supportMoney) {
		this.supportMoney = supportMoney;
	}

	@Column(name = "order_state", nullable = false, length = 6)
	public String getOrderState() {
		return this.orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	@Column(name = "project_title", nullable = false, length = 80)
	public String getProjectTitle() {
		return this.projectTitle;
	}

	public void setProjectTitle(String projectTitle) {
		this.projectTitle = projectTitle;
	}

	@Column(name = "project_head", length = 100)
	public String getProjectHead() {
		return this.projectHead;
	}

	public void setProjectHead(String projectHead) {
		this.projectHead = projectHead;
	}

	@Column(name = "address", nullable = false, length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "logistics", length = 45)
	public String getLogistics() {
		return this.logistics;
	}

	public void setLogistics(String logistics) {
		this.logistics = logistics;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderViewId))
			return false;
		OrderViewId castOther = (OrderViewId) other;

		return (this.getOrderId() == castOther.getOrderId()) && (this.getUserId() == castOther.getUserId())
				&& (this.getProjectId() == castOther.getProjectId()) && (this.getReturnId() == castOther.getReturnId())
				&& ((this.getReturnImage() == castOther.getReturnImage())
						|| (this.getReturnImage() != null && castOther.getReturnImage() != null
								&& this.getReturnImage().equals(castOther.getReturnImage())))
				&& ((this.getOrderTime() == castOther.getOrderTime()) || (this.getOrderTime() != null
						&& castOther.getOrderTime() != null && this.getOrderTime().equals(castOther.getOrderTime())))
				&& (this.getSupportMoney() == castOther.getSupportMoney())
				&& ((this.getOrderState() == castOther.getOrderState()) || (this.getOrderState() != null
						&& castOther.getOrderState() != null && this.getOrderState().equals(castOther.getOrderState())))
				&& ((this.getProjectTitle() == castOther.getProjectTitle())
						|| (this.getProjectTitle() != null && castOther.getProjectTitle() != null
								&& this.getProjectTitle().equals(castOther.getProjectTitle())))
				&& ((this.getProjectHead() == castOther.getProjectHead())
						|| (this.getProjectHead() != null && castOther.getProjectHead() != null
								&& this.getProjectHead().equals(castOther.getProjectHead())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& ((this.getLogistics() == castOther.getLogistics()) || (this.getLogistics() != null
						&& castOther.getLogistics() != null && this.getLogistics().equals(castOther.getLogistics())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getUserId();
		result = 37 * result + this.getProjectId();
		result = 37 * result + this.getReturnId();
		result = 37 * result + (getReturnImage() == null ? 0 : this.getReturnImage().hashCode());
		result = 37 * result + (getOrderTime() == null ? 0 : this.getOrderTime().hashCode());
		result = 37 * result + this.getSupportMoney();
		result = 37 * result + (getOrderState() == null ? 0 : this.getOrderState().hashCode());
		result = 37 * result + (getProjectTitle() == null ? 0 : this.getProjectTitle().hashCode());
		result = 37 * result + (getProjectHead() == null ? 0 : this.getProjectHead().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + (getLogistics() == null ? 0 : this.getLogistics().hashCode());
		return result;
	}

}
