package com.zcadmin.entity;
// Generated 2016-5-1 17:34:38 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectViewId generated by hbm2java
 */
@Embeddable
public class ProjectViewId implements java.io.Serializable {

	private int projectId;
	private String projectOwnerId;
	private String projectOwnerName;
	private String projectOwnerAvatar;
	private String projectTitle;
	private String projectClass;
	private String projectHead;
	private String projectDescription;
	private byte[] projectContent;
	private String projectAddressProvince;
	private String projectAddressCity;
	private int projectMoney;
	private Integer projectMoneyRecive;
	private int projectDays;
	private Date projectStart;
	private Date projectEnd;
	private Integer projectDayLeft;
	private String projectState;
	private BigDecimal projectProcess;

	public ProjectViewId() {
	}

	public ProjectViewId(int projectId, String projectOwnerId, String projectOwnerName, String projectTitle,
			String projectClass, String projectDescription, byte[] projectContent, String projectAddressProvince,
			String projectAddressCity, int projectMoney, int projectDays, String projectState) {
		this.projectId = projectId;
		this.projectOwnerId = projectOwnerId;
		this.projectOwnerName = projectOwnerName;
		this.projectTitle = projectTitle;
		this.projectClass = projectClass;
		this.projectDescription = projectDescription;
		this.projectContent = projectContent;
		this.projectAddressProvince = projectAddressProvince;
		this.projectAddressCity = projectAddressCity;
		this.projectMoney = projectMoney;
		this.projectDays = projectDays;
		this.projectState = projectState;
	}

	public ProjectViewId(int projectId, String projectOwnerId, String projectOwnerName, String projectOwnerAvatar,
			String projectTitle, String projectClass, String projectHead, String projectDescription,
			byte[] projectContent, String projectAddressProvince, String projectAddressCity, int projectMoney,
			Integer projectMoneyRecive, int projectDays, Date projectStart, Date projectEnd, Integer projectDayLeft,
			String projectState, BigDecimal projectProcess) {
		this.projectId = projectId;
		this.projectOwnerId = projectOwnerId;
		this.projectOwnerName = projectOwnerName;
		this.projectOwnerAvatar = projectOwnerAvatar;
		this.projectTitle = projectTitle;
		this.projectClass = projectClass;
		this.projectHead = projectHead;
		this.projectDescription = projectDescription;
		this.projectContent = projectContent;
		this.projectAddressProvince = projectAddressProvince;
		this.projectAddressCity = projectAddressCity;
		this.projectMoney = projectMoney;
		this.projectMoneyRecive = projectMoneyRecive;
		this.projectDays = projectDays;
		this.projectStart = projectStart;
		this.projectEnd = projectEnd;
		this.projectDayLeft = projectDayLeft;
		this.projectState = projectState;
		this.projectProcess = projectProcess;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "project_owner_id", nullable = false, length = 10)
	public String getProjectOwnerId() {
		return this.projectOwnerId;
	}

	public void setProjectOwnerId(String projectOwnerId) {
		this.projectOwnerId = projectOwnerId;
	}

	@Column(name = "project_owner_name", nullable = false, length = 20)
	public String getProjectOwnerName() {
		return this.projectOwnerName;
	}

	public void setProjectOwnerName(String projectOwnerName) {
		this.projectOwnerName = projectOwnerName;
	}

	@Column(name = "project_owner_avatar", length = 100)
	public String getProjectOwnerAvatar() {
		return this.projectOwnerAvatar;
	}

	public void setProjectOwnerAvatar(String projectOwnerAvatar) {
		this.projectOwnerAvatar = projectOwnerAvatar;
	}

	@Column(name = "project_title", nullable = false, length = 80)
	public String getProjectTitle() {
		return this.projectTitle;
	}

	public void setProjectTitle(String projectTitle) {
		this.projectTitle = projectTitle;
	}

	@Column(name = "project_class", nullable = false, length = 10)
	public String getProjectClass() {
		return this.projectClass;
	}

	public void setProjectClass(String projectClass) {
		this.projectClass = projectClass;
	}

	@Column(name = "project_head", length = 100)
	public String getProjectHead() {
		return this.projectHead;
	}

	public void setProjectHead(String projectHead) {
		this.projectHead = projectHead;
	}

	@Column(name = "project_description", nullable = false, length = 150)
	public String getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

	@Column(name = "project_content", nullable = false)
	public byte[] getProjectContent() {
		return this.projectContent;
	}

	public void setProjectContent(byte[] projectContent) {
		this.projectContent = projectContent;
	}

	@Column(name = "project_address_province", nullable = false, length = 10)
	public String getProjectAddressProvince() {
		return this.projectAddressProvince;
	}

	public void setProjectAddressProvince(String projectAddressProvince) {
		this.projectAddressProvince = projectAddressProvince;
	}

	@Column(name = "project_address_city", nullable = false, length = 10)
	public String getProjectAddressCity() {
		return this.projectAddressCity;
	}

	public void setProjectAddressCity(String projectAddressCity) {
		this.projectAddressCity = projectAddressCity;
	}

	@Column(name = "project_money", nullable = false)
	public int getProjectMoney() {
		return this.projectMoney;
	}

	public void setProjectMoney(int projectMoney) {
		this.projectMoney = projectMoney;
	}

	@Column(name = "project_money_recive")
	public Integer getProjectMoneyRecive() {
		return this.projectMoneyRecive;
	}

	public void setProjectMoneyRecive(Integer projectMoneyRecive) {
		this.projectMoneyRecive = projectMoneyRecive;
	}

	@Column(name = "project_days", nullable = false)
	public int getProjectDays() {
		return this.projectDays;
	}

	public void setProjectDays(int projectDays) {
		this.projectDays = projectDays;
	}

	@Column(name = "project_start", length = 19)
	public Date getProjectStart() {
		return this.projectStart;
	}

	public void setProjectStart(Date projectStart) {
		this.projectStart = projectStart;
	}

	@Column(name = "project_end", length = 19)
	public Date getProjectEnd() {
		return this.projectEnd;
	}

	public void setProjectEnd(Date projectEnd) {
		this.projectEnd = projectEnd;
	}

	@Column(name = "project_day_left")
	public Integer getProjectDayLeft() {
		return this.projectDayLeft;
	}

	public void setProjectDayLeft(Integer projectDayLeft) {
		this.projectDayLeft = projectDayLeft;
	}

	@Column(name = "project_state", nullable = false, length = 20)
	public String getProjectState() {
		return this.projectState;
	}

	public void setProjectState(String projectState) {
		this.projectState = projectState;
	}

	@Column(name = "project_process", precision = 16)
	public BigDecimal getProjectProcess() {
		return this.projectProcess;
	}

	public void setProjectProcess(BigDecimal projectProcess) {
		this.projectProcess = projectProcess;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectViewId))
			return false;
		ProjectViewId castOther = (ProjectViewId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& ((this.getProjectOwnerId() == castOther.getProjectOwnerId())
						|| (this.getProjectOwnerId() != null && castOther.getProjectOwnerId() != null
								&& this.getProjectOwnerId().equals(castOther.getProjectOwnerId())))
				&& ((this.getProjectOwnerName() == castOther.getProjectOwnerName())
						|| (this.getProjectOwnerName() != null && castOther.getProjectOwnerName() != null
								&& this.getProjectOwnerName().equals(castOther.getProjectOwnerName())))
				&& ((this.getProjectOwnerAvatar() == castOther.getProjectOwnerAvatar())
						|| (this.getProjectOwnerAvatar() != null && castOther.getProjectOwnerAvatar() != null
								&& this.getProjectOwnerAvatar().equals(castOther.getProjectOwnerAvatar())))
				&& ((this.getProjectTitle() == castOther.getProjectTitle())
						|| (this.getProjectTitle() != null && castOther.getProjectTitle() != null
								&& this.getProjectTitle().equals(castOther.getProjectTitle())))
				&& ((this.getProjectClass() == castOther.getProjectClass())
						|| (this.getProjectClass() != null && castOther.getProjectClass() != null
								&& this.getProjectClass().equals(castOther.getProjectClass())))
				&& ((this.getProjectHead() == castOther.getProjectHead())
						|| (this.getProjectHead() != null && castOther.getProjectHead() != null
								&& this.getProjectHead().equals(castOther.getProjectHead())))
				&& ((this.getProjectDescription() == castOther.getProjectDescription())
						|| (this.getProjectDescription() != null && castOther.getProjectDescription() != null
								&& this.getProjectDescription().equals(castOther.getProjectDescription())))
				&& ((this.getProjectContent() == castOther.getProjectContent())
						|| (this.getProjectContent() != null && castOther.getProjectContent() != null
								&& Arrays.equals(this.getProjectContent(), castOther.getProjectContent())))
				&& ((this.getProjectAddressProvince() == castOther.getProjectAddressProvince())
						|| (this.getProjectAddressProvince() != null && castOther.getProjectAddressProvince() != null
								&& this.getProjectAddressProvince().equals(castOther.getProjectAddressProvince())))
				&& ((this.getProjectAddressCity() == castOther.getProjectAddressCity())
						|| (this.getProjectAddressCity() != null && castOther.getProjectAddressCity() != null
								&& this.getProjectAddressCity().equals(castOther.getProjectAddressCity())))
				&& (this.getProjectMoney() == castOther.getProjectMoney())
				&& ((this.getProjectMoneyRecive() == castOther.getProjectMoneyRecive())
						|| (this.getProjectMoneyRecive() != null && castOther.getProjectMoneyRecive() != null
								&& this.getProjectMoneyRecive().equals(castOther.getProjectMoneyRecive())))
				&& (this.getProjectDays() == castOther.getProjectDays())
				&& ((this.getProjectStart() == castOther.getProjectStart())
						|| (this.getProjectStart() != null && castOther.getProjectStart() != null
								&& this.getProjectStart().equals(castOther.getProjectStart())))
				&& ((this.getProjectEnd() == castOther.getProjectEnd()) || (this.getProjectEnd() != null
						&& castOther.getProjectEnd() != null && this.getProjectEnd().equals(castOther.getProjectEnd())))
				&& ((this.getProjectDayLeft() == castOther.getProjectDayLeft())
						|| (this.getProjectDayLeft() != null && castOther.getProjectDayLeft() != null
								&& this.getProjectDayLeft().equals(castOther.getProjectDayLeft())))
				&& ((this.getProjectState() == castOther.getProjectState())
						|| (this.getProjectState() != null && castOther.getProjectState() != null
								&& this.getProjectState().equals(castOther.getProjectState())))
				&& ((this.getProjectProcess() == castOther.getProjectProcess())
						|| (this.getProjectProcess() != null && castOther.getProjectProcess() != null
								&& this.getProjectProcess().equals(castOther.getProjectProcess())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + (getProjectOwnerId() == null ? 0 : this.getProjectOwnerId().hashCode());
		result = 37 * result + (getProjectOwnerName() == null ? 0 : this.getProjectOwnerName().hashCode());
		result = 37 * result + (getProjectOwnerAvatar() == null ? 0 : this.getProjectOwnerAvatar().hashCode());
		result = 37 * result + (getProjectTitle() == null ? 0 : this.getProjectTitle().hashCode());
		result = 37 * result + (getProjectClass() == null ? 0 : this.getProjectClass().hashCode());
		result = 37 * result + (getProjectHead() == null ? 0 : this.getProjectHead().hashCode());
		result = 37 * result + (getProjectDescription() == null ? 0 : this.getProjectDescription().hashCode());
		result = 37 * result + (getProjectContent() == null ? 0 : Arrays.hashCode(this.getProjectContent()));
		result = 37 * result + (getProjectAddressProvince() == null ? 0 : this.getProjectAddressProvince().hashCode());
		result = 37 * result + (getProjectAddressCity() == null ? 0 : this.getProjectAddressCity().hashCode());
		result = 37 * result + this.getProjectMoney();
		result = 37 * result + (getProjectMoneyRecive() == null ? 0 : this.getProjectMoneyRecive().hashCode());
		result = 37 * result + this.getProjectDays();
		result = 37 * result + (getProjectStart() == null ? 0 : this.getProjectStart().hashCode());
		result = 37 * result + (getProjectEnd() == null ? 0 : this.getProjectEnd().hashCode());
		result = 37 * result + (getProjectDayLeft() == null ? 0 : this.getProjectDayLeft().hashCode());
		result = 37 * result + (getProjectState() == null ? 0 : this.getProjectState().hashCode());
		result = 37 * result + (getProjectProcess() == null ? 0 : this.getProjectProcess().hashCode());
		return result;
	}

}
