package com.zcadmin.entity;
// Generated 2016-5-1 17:34:38 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Returns generated by hbm2java
 */
@Entity
@Table(name = "returns", catalog = "gmczc")
public class Returns implements java.io.Serializable {

	private ReturnsId id;
	private int supportMoney;
	private String returnContent;
	private Integer supportLimit;
	private Integer freight;
	private Integer returnTime;
	private String returnType;
	private String returnImage;
	private Integer supportCount;

	public Returns() {
	}

	public Returns(ReturnsId id, int supportMoney, String returnContent) {
		this.id = id;
		this.supportMoney = supportMoney;
		this.returnContent = returnContent;
	}

	public Returns(ReturnsId id, int supportMoney, String returnContent, Integer supportLimit, Integer freight,
			Integer returnTime, String returnType, String returnImage, Integer supportCount) {
		this.id = id;
		this.supportMoney = supportMoney;
		this.returnContent = returnContent;
		this.supportLimit = supportLimit;
		this.freight = freight;
		this.returnTime = returnTime;
		this.returnType = returnType;
		this.returnImage = returnImage;
		this.supportCount = supportCount;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "returnId", column = @Column(name = "return_id", nullable = false) ),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id", nullable = false) ) })
	public ReturnsId getId() {
		return this.id;
	}

	public void setId(ReturnsId id) {
		this.id = id;
	}

	@Column(name = "support_money", nullable = false)
	public int getSupportMoney() {
		return this.supportMoney;
	}

	public void setSupportMoney(int supportMoney) {
		this.supportMoney = supportMoney;
	}

	@Column(name = "return_content", nullable = false, length = 1000)
	public String getReturnContent() {
		return this.returnContent;
	}

	public void setReturnContent(String returnContent) {
		this.returnContent = returnContent;
	}

	@Column(name = "support_limit")
	public Integer getSupportLimit() {
		return this.supportLimit;
	}

	public void setSupportLimit(Integer supportLimit) {
		this.supportLimit = supportLimit;
	}

	@Column(name = "freight")
	public Integer getFreight() {
		return this.freight;
	}

	public void setFreight(Integer freight) {
		this.freight = freight;
	}

	@Column(name = "return_time")
	public Integer getReturnTime() {
		return this.returnTime;
	}

	public void setReturnTime(Integer returnTime) {
		this.returnTime = returnTime;
	}

	@Column(name = "return_type", length = 8)
	public String getReturnType() {
		return this.returnType;
	}

	public void setReturnType(String returnType) {
		this.returnType = returnType;
	}

	@Column(name = "return_image", length = 100)
	public String getReturnImage() {
		return this.returnImage;
	}

	public void setReturnImage(String returnImage) {
		this.returnImage = returnImage;
	}

	@Column(name = "support_count")
	public Integer getSupportCount() {
		return this.supportCount;
	}

	public void setSupportCount(Integer supportCount) {
		this.supportCount = supportCount;
	}

}
