package com.zcadmin.entity;
// Generated 2016-5-1 17:34:38 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReturnsId generated by hbm2java
 */
@Embeddable
public class ReturnsId implements java.io.Serializable {

	private int returnId;
	private int projectId;

	public ReturnsId() {
	}

	public ReturnsId(int returnId, int projectId) {
		this.returnId = returnId;
		this.projectId = projectId;
	}

	@Column(name = "return_id", nullable = false)
	public int getReturnId() {
		return this.returnId;
	}

	public void setReturnId(int returnId) {
		this.returnId = returnId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReturnsId))
			return false;
		ReturnsId castOther = (ReturnsId) other;

		return (this.getReturnId() == castOther.getReturnId()) && (this.getProjectId() == castOther.getProjectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getReturnId();
		result = 37 * result + this.getProjectId();
		return result;
	}

}
