package com.zcadmin.entity;
// Generated 2016-5-1 17:34:38 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "gmczc", uniqueConstraints = { @UniqueConstraint(columnNames = "user_email"),
		@UniqueConstraint(columnNames = "user_name") })
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPass;
	private String userEmail;
	private String userSex;
	private String userAvatar;
	private String userAddressProvince;
	private String userAddressCity;
	private String userPhone;
	private Integer userAccount;
	private String userTrueName;
	private Integer userType;
	private String userCode;

	public User() {
	}

	public User(String userName, String userPass, String userEmail) {
		this.userName = userName;
		this.userPass = userPass;
		this.userEmail = userEmail;
	}

	public User(String userName, String userPass, String userEmail, String userSex, String userAvatar,
			String userAddressProvince, String userAddressCity, String userPhone, Integer userAccount,
			String userTrueName, Integer userType, String userCode) {
		this.userName = userName;
		this.userPass = userPass;
		this.userEmail = userEmail;
		this.userSex = userSex;
		this.userAvatar = userAvatar;
		this.userAddressProvince = userAddressProvince;
		this.userAddressCity = userAddressCity;
		this.userPhone = userPhone;
		this.userAccount = userAccount;
		this.userTrueName = userTrueName;
		this.userType = userType;
		this.userCode = userCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", unique = true, nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_pass", nullable = false, length = 16)
	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	@Column(name = "user_email", unique = true, nullable = false, length = 45)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_sex", length = 2)
	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	@Column(name = "user_avatar", length = 100)
	public String getUserAvatar() {
		return this.userAvatar;
	}

	public void setUserAvatar(String userAvatar) {
		this.userAvatar = userAvatar;
	}

	@Column(name = "user_address_province", length = 45)
	public String getUserAddressProvince() {
		return this.userAddressProvince;
	}

	public void setUserAddressProvince(String userAddressProvince) {
		this.userAddressProvince = userAddressProvince;
	}

	@Column(name = "user_address_city", length = 45)
	public String getUserAddressCity() {
		return this.userAddressCity;
	}

	public void setUserAddressCity(String userAddressCity) {
		this.userAddressCity = userAddressCity;
	}

	@Column(name = "user_phone", length = 11)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_account")
	public Integer getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(Integer userAccount) {
		this.userAccount = userAccount;
	}

	@Column(name = "user_true_name", length = 10)
	public String getUserTrueName() {
		return this.userTrueName;
	}

	public void setUserTrueName(String userTrueName) {
		this.userTrueName = userTrueName;
	}

	@Column(name = "user_type")
	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	@Column(name = "user_code", length = 20)
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

}
